baseURL = "https://harrysarson.github.io/blog/"
languageCode = "en-us"
title = "Harry Sarson's Thoughts"
theme = "beautifulhugo"

pygmentsCodeFences = true
pygmentsUseClasses = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
